# Generated by Django 2.2.8 on 2019-12-12 23:04

import account.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191212_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=stdimage.models.StdImageField(null=True, upload_to=account.models.get_image_path, verbose_name='profile picture'),
        ),
    ]
