# Generated by Django 2.2.8 on 2019-12-13 07:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191213_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/', verbose_name='profile picture'),
        ),
    ]
