# Generated by Django 2.2.8 on 2019-12-13 08:38

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20191213_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=account.models.get_image_path),
        ),
    ]
