# Generated by Django 2.2.8 on 2019-12-14 11:03

import account.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20191214_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=stdimage.models.StdImageField(null=True, upload_to=account.models.get_image_path, verbose_name='profile picture'),
        ),
    ]
