# Generated by Django 2.2.8 on 2019-12-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_userauthenticate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuthenticate',
        ),
    ]
