# Generated by Django 2.2.9 on 2019-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20191216_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
