# Generated by Django 2.2.9 on 2019-12-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_post_published_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date2',
        ),
    ]
