# Generated by Django 2.2.9 on 2019-12-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20191224_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
