# Generated by Django 2.2.9 on 2019-12-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
