# Generated by Django 2.2.9 on 2020-01-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment_text',
        ),
    ]
