# Generated by Django 2.2.9 on 2020-01-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20200102_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
