# Generated by Django 2.2.9 on 2020-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_auto_20200102_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likePost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=250, verbose_name='コメント内容'),
        ),
    ]
