# Generated by Django 2.2.9 on 2020-01-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_remove_post_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
