# Generated by Django 2.2.9 on 2020-01-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20200113_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
