# Generated by Django 2.2.9 on 2020-01-17 11:17

import account.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_remove_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=account.models.get_image_path),
        ),
    ]
